name: PMD Check

on: [push, pull_request]

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run PMD
        run: mvn pmd:check
